language: php
php:
  - '8.0'

dist: bionic

env:
  global:
    - XDEBUG_MODE=coverage

services:
  - mysql

before_script:
  - cp .env.example .env
  - mysql -e "create database shoppingcart"
  - composer self-update
  - composer install --no-interaction --prefer-source
  - php artisan key:generate
  - php artisan migrate

script:
  - vendor/bin/phpunit --coverage-clover coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
